### ISSUE TITLE
protobuf报错啦,作者

### ISSUE THREAD

**Issue by SwpuEsine** [ccfish86/sctalk#68]
protobuf报错啦,作者

**Comment by ccfish86** [comment]
哪个端报错？ 需要注意下protobuf 不同版本会有点差异

**Comment by SwpuEsine** [comment]
搞定了感谢,版本有问题,maven里面的版本不太对


??????
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ccfish86/sctalk"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月20日(星期二) 晚上6:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ccfish86/sctalk] protobuf报错啦,作者 (Issue #68)





 
哪个端报错？ 需要注意下protobuf 不同版本会有点差异
